name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build_windows:
    name: "Windows Build"

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.2.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        install-deps: 'true'
        modules: 'qtwidget qtgui qtsvg qtnetwork'
        setup-python: 'true'
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        
    - uses: ilammy/msvc-dev-cmd@v1
      
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "NMake Makefiles"

    - name: Build
      # Build your program with the given configuration
      run: cmake --build . --config ${{env.BUILD_TYPE}}
      
    - name: Package Dependencies
      run: |
        mkdir with_deps
        mv lunar-client-qt.exe with_deps/
        windeployqt with_deps/ --compiler-runtime --no-opengl-sw --no-virtualkeyboard --no-system-d3d-compiler --no-translations --no-quick-import
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: ./with_deps
  build_mac:
    name: "MacOS Build"
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.2'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          install-deps: 'true'
          modules: 'qtwidget qtgui qtsvg qtnetwork'
          setup-python: 'false'
        
      - name: Configure CMake
        run: cmake . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: make
        
      - uses: actions/upload-artifact@v2
        with:
          name: mac
          path: ./lunar-client-qt.app
          
          
  arch_build:
    name: "Arch Linux Build"
    
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    steps: 
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          pacman -Syu --noconfirm qt6-base qt6-svg cmake base-devel
          
      - name: Configure CMake
        run: cmake . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
       
      - name: Build
        run: make
        
      - uses: actions/upload-artifact@v2
        with:
          name: linux
          path: ./lunar-client-qt
    
