name: 构建和发布

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build_windows:
    name: "Windows Build"

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: MINGW64
        install: >-
          git
          zip
          mingw-w64-x86_64-qt5-base
          mingw-w64-x86_64-qt5-tools
          mingw-w64-x86_64-qt5-svg
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-jq
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-openssl

    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: 获取标签
      run: git fetch --prune --tags -f

    - name: 配置 CMake
      run: cmake . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: 建造
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: 将构建文件移动到新目录
      shell: powershell
      run: |
        mkdir 'Lunar Client Qt'
        mv -Path @('lunar-client-qt.exe';jq -r '.agentsDestDir' config.json) -Destination 'Lunar Client Qt'

    - name: 包 Qt
      run: windeployqt 'Lunar Client Qt' --compiler-runtime --no-angle --no-opengl-sw --no-virtualkeyboard --no-webkit2 --no-system-d3d-compiler --no-translations --no-quick-import

    - name: 打包其他依赖项
      working-directory: 'Lunar Client Qt'
      run: >-
        ldd lunar-client-qt |
        sed -n 's/.*=> \(\/mingw64.*\) .*/\1/p' |
        xargs cp -n -t .
        
        cp -t . /mingw64/bin/{libssl*,libcrypto*}.dll

    - name: 压缩
      run: zip -9 -r windows.zip 'Lunar Client Qt'

    - name: 上传工件
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: ./windows.zip
  build_mac:
    name: "MacOS Build"
    runs-on: macos-10.15
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Fetch Tags
        run: git fetch --prune --tags -f
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: '5.15.2'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          setup-python: 'false'
        
      - name: Configure CMake
        run: cmake . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: make
        
      - name: Package Dependencies
        run: |
          macdeployqt lunar-client-qt.app
          
      - name: Compress
        run: |
          tar -czvf mac.tar.gz lunar-client-qt.app
          
      - uses: actions/upload-artifact@v2
        with:
          name: mac
          path: ./mac.tar.gz
          
          
  build_arch:
    name: "Arch Linux Build"
    
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install Packages
        run: |
          pacman -Syu --noconfirm --needed qt5-base qt5-svg cmake base-devel git jq

      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Mark Repository as Safe
        run: git config --global safe.directory "$GITHUB_WORKSPACE"

      - name: Fetch Tags
        run: git fetch --prune --tags -f

      - name: Configure CMake
        run: cmake . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        
      - name: Build
        run: make

      - name: Compress
        run: |
          mkdir Lunar\ Client\ Qt
          jq '.agentsDestDir' config.json | xargs mv -t Lunar\ Client\ Qt/ lunar-client-qt
          tar czvf linux.tar.gz Lunar\ Client\ Qt/

      - uses: actions/upload-artifact@v2
        with:
          name: linux
          path: ./linux.tar.gz

  create_release:
    name: "Create Release"
    needs: [build_windows, build_mac, build_arch]
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    steps:
    - name: Download Builds
      uses: actions/download-artifact@v3

    - name: Variables
      id: variables
      run: |
        echo "::set-output name=version::${GITHUB_REF_NAME#v}"

    - name: Create Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        name: ${{ steps.variables.outputs.version }}
        draft: true
        fail_on_unmatched_files: true
        files: |
          linux/linux.tar.gz
          mac/mac.tar.gz
          windows/windows.zip