name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build_windows:
    name: "Windows Build"

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Qt & MinGW
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw81'
        tools: 'tools_mingw,8.1.0-1-202004170606,qt.tools.win64_mingw810'
      
    - name: Configure CMake
      run: cmake . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "MinGW Makefiles"

    - name: Build
      run: cmake --build . --config ${{env.BUILD_TYPE}}
      
    - name: Package Dependencies
      shell: bash
      run: |
        mkdir with_deps
        mv lunar-client-qt.exe with_deps/
        PATH="$IQTA_TOOLS/mingw810_64/bin":$PATH windeployqt with_deps/ --compiler-runtime --no-angle --no-opengl-sw --no-virtualkeyboard --no-webkit2 --no-system-d3d-compiler --no-translations --no-quick-import  
    - name: Upload Artifiact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: ./with_deps
  build_mac:
    name: "MacOS Build"
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: '6.2.2'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
        
      - name: Configure CMake
        run: cmake . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: make
        
      - uses: actions/upload-artifact@v2
        with:
          name: mac
          path: ./lunar-client-qt.app
          
          
  arch_build:
    name: "Arch Linux Build"
    
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    steps: 
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          pacman -Syu --noconfirm qt6-base qt6-svg cmake base-devel
          
      - name: Configure CMake
        run: cmake . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
       
      - name: Build
        run: make
        
      - uses: actions/upload-artifact@v2
        with:
          name: linux
          path: ./lunar-client-qt
    
